import { z } from "zod";
import { LeagueCompetitionLevel, LeagueType, Sport } from "@prisma/client";

/* model Player {
     id         String            @id @default(uuid()) @db.Uuid
     user       User              @relation("players", fields: [userId], references: [id])
     userId     String            @db.Uuid
     createdAt  DateTime          @default(now())
     updatedAt  DateTime          @updatedAt
     playerType LeaguePlayerType? @default(value: PLAYER)
     // Note: We will have to figure out a way to ensure that participants of type PLAYER always belong to a team.  The
     // team needs to be optional for cases where the participant is of type ADMIN or REFEREE.
     team       Team              @relation("players", fields: [teamId], references: [id])
     teamId     String            @db.Uuid */

/*   @@unique([userId, teamId])
   } */

/* Note:  At this point in time, this schema is only being used for the creation of Players.  Eventually, that flow will
   be more closely tied to the registration/invite process, and the usage of this schema and its properties may be
   subject to change.

   - The Clerk ID will be generated by the server when the user is created, but this may be adjusted in the future so
     users are created after they are created in Clerk via webhooks or middleware.
   - Eventually, we will need to incorporate the organization.  For now, we are assuming organization-less users.  */
export const UserSchema = z.object({});

/* model User {
     id                   String        @id @default(uuid()) @db.Uuid
     clerkId              String        @unique
     firstName            String
     lastName             String
     profileImageUrl      String?
     gender               Gender        @default(value: NON_BINARY)
     emailAddress         String
     createdAt            DateTime      @default(now())
     updatedAt            DateTime      @updatedAt
     org                  Org?          @relation("orgUsers", fields: [orgId], references: [id])
     orgId                String?       @db.Uuid
     roles                UserRole[]    @default(value: [])
     // Users are only created when Clerk data for the user exists - so a default value of "now" makes sense here.
     lastUpdatedFromClerk DateTime      @default(now())
     players              Player[]      @relation("players")
     createdLocations     Location[]    @relation("createdLocations")
     uploadedFiles        FileUpload[]  @relation("uploadedFiles")
     staffPositions       LeagueStaff[] @relation("staff")
   } */
