/*
This file contains the icons that are used in the application.  When additional icons are required, they should be
imported in this file and added to the `IconRegistry` array.
*/
import {
  faCircleQuestion,
  faFileImage,
  faFileVideo,
  faFileAudio,
  faFileZipper,
  faFilePdf,
  faFilePowerpoint,
  faFileExcel,
  faFileWord,
  faFile,
  faTrashAlt,
  faFolderOpen as faRegularFolderOpen,
} from "@fortawesome/free-regular-svg-icons";
import {
  faArrowDown,
  faArrowUp,
  faDatabase,
  faTriangleExclamation,
  faCircleCheck,
  faCircleExclamation,
  faXmark,
  faUserCircle,
  faChevronDown,
  faFileCsv,
  faBuildingColumns,
  faFileImport,
  faCircleNotch,
  faServer,
  faCaretDown,
  faCaretUp,
  faCircleXmark,
  faFilter,
  faCameraAlt,
  faFolderOpen as faSolidFolderOpen,
  faCopy,
  faUsers,
  faBookOpen,
  faCirclePlus,
  faAddressBook,
  faBook,
  faCopyright,
} from "@fortawesome/free-solid-svg-icons";

export const ICON_REGISTRY = [
  faArrowDown,
  faArrowUp,
  faDatabase,
  faTriangleExclamation,
  faCircleCheck,
  faCircleExclamation,
  faXmark,
  faUserCircle,
  faChevronDown,
  faCircleQuestion,
  faFileImage,
  faFileVideo,
  faFileAudio,
  faFileZipper,
  faFilePdf,
  faFilePowerpoint,
  faFileExcel,
  faFileWord,
  faFileCsv,
  faFile,
  faBuildingColumns,
  faFileImport,
  faCircleNotch,
  faServer,
  faCaretDown,
  faCaretUp,
  faCircleXmark,
  faTrashAlt,
  faFilter,
  faCameraAlt,
  faRegularFolderOpen,
  faSolidFolderOpen,
  faCopy,
  faUsers,
  faBookOpen,
  faAddressBook,
  faBook,
  faCirclePlus,
  faCopyright,
] as const;
