/*
This file contains the icons that are used in the application.  When additional icons are required, they should be
imported in this file and added to the `IconRegistry` array.
*/
import { faCircleQuestion, faTrashAlt, faPenToSquare, faImage } from "@fortawesome/free-regular-svg-icons";
import {
  faArrowDown,
  faArrowUp,
  faTriangleExclamation,
  faCircleCheck,
  faCircleExclamation,
  faXmark,
  faChevronDown,
  faCircleNotch,
  faCaretDown,
  faCaretUp,
  faCircleXmark,
  faCopy,
  faCirclePlus,
  faHockeyPuck,
  faSitemap,
  faPeopleGroup,
  faPeopleArrows,
  faCircleHalfStroke,
  faMedal,
  faHouseChimney,
  faTableTennisPaddleBall,
  faEllipsis,
  faMagnifyingGlass,
} from "@fortawesome/free-solid-svg-icons";

export const ICON_REGISTRY = [
  faArrowDown,
  faArrowUp,
  faTriangleExclamation,
  faCircleCheck,
  faCircleExclamation,
  faXmark,
  faChevronDown,
  faCircleQuestion,
  faCircleNotch,
  faCaretDown,
  faCaretUp,
  faCircleXmark,
  faTrashAlt,
  faCopy,
  faCirclePlus,
  faHockeyPuck,
  faSitemap,
  faPeopleGroup,
  faPeopleArrows,
  faCircleHalfStroke,
  faMedal,
  faHouseChimney,
  faTableTennisPaddleBall,
  faPenToSquare,
  faEllipsis,
  faMagnifyingGlass,
  faImage,
] as const;
